name: itjobs
channels:
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - json5=0.10.0
  - jsonpointer=2.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=17.2
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.9.12
  - lz4-c=1.9.4
  - m2w64-bwidget=1.9.10
  - m2w64-bzip2=1.0.6
  - m2w64-expat=2.1.1
  - m2w64-fftw=3.3.4
  - m2w64-flac=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-gsl=2.1
  - m2w64-icu=58.2
  - m2w64-libiconv=1.14
  - m2w64-libjpeg-turbo=1.4.2
  - m2w64-libogg=1.3.2
  - m2w64-libpng=1.6.21
  - m2w64-libsndfile=1.0.26
  - m2w64-libtiff=4.0.6
  - m2w64-libvorbis=1.3.5
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-libxml2=2.9.3
  - m2w64-mpfr=3.1.4
  - m2w64-pcre2=10.34
  - m2w64-speex=1.2rc2
  - m2w64-speexdsp=1.2rc3
  - m2w64-tcl=8.6.5
  - m2w64-tk=8.6.5
  - m2w64-tktable=2.10
  - m2w64-wineditline=2.101
  - m2w64-xz=5.2.2
  - m2w64-zlib=1.2.8
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - msys2-conda-epoch=20160418
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.4.1
  - outcome=1.1.0
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2024.1
  - pywin32=308
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.1.3
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-blob=1.2.4
  - r-boot=1.3_28.1
  - r-broom=1.0.5
  - r-bslib=0.5.0
  - r-cachem=1.1.0
  - r-callr=3.7.3
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_22
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-cluster=2.1.6
  - r-codetools=0.2_19
  - r-colorspace=2.1_0
  - r-commonmark=1.9.1
  - r-conflicted=1.2.0
  - r-cpp11=0.4.7
  - r-crayon=1.5.2
  - r-crul=1.4.0
  - r-curl=4.3.3
  - r-data.table=1.15.4
  - r-dbi=1.1.3
  - r-dbplyr=2.3.2
  - r-diagram=1.6.5
  - r-digest=0.6.36
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-e1071=1.7_14
  - r-ellipsis=0.3.2
  - r-essentials=4.1
  - r-evaluate=0.21
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.1
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_87
  - r-formatr=1.14
  - r-fs=1.6.4
  - r-future=1.32.0
  - r-future.apply=1.11.0
  - r-gargle=1.4.0
  - r-generics=0.1.3
  - r-ggplot2=3.4.2
  - r-gistr=0.9.0
  - r-glmnet=4.1_2
  - r-globals=0.16.2
  - r-glue=1.7.0
  - r-googledrive=2.1.0
  - r-googlesheets4=1.1.0
  - r-gower=1.0.1
  - r-gtable=0.3.3
  - r-hardhat=1.3.0
  - r-haven=2.5.4
  - r-hexbin=1.28.3
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.2
  - r-httpcode=0.3.0
  - r-httpuv=1.6.15
  - r-httr=1.4.6
  - r-ids=1.0.1
  - r-ipred=0.9_15
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-kernsmooth=2.23_24
  - r-knitr=1.43
  - r-labeling=0.4.2
  - r-later=1.3.2
  - r-lattice=0.22_6
  - r-lava=1.7.2.1
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.3
  - r-listenv=0.9.0
  - r-lobstr=1.1.2
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-maps=3.4.2
  - r-mass=7.3_58.3
  - r-matrix=1.6_5
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.0
  - r-nlme=3.1_165
  - r-nnet=7.3_19
  - r-numderiv=2016.8_1.1
  - r-openssl=2.0.6
  - r-parallelly=1.37.1
  - r-pbdzmq=0.3_11
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.9
  - r-prettyunits=1.1.1
  - r-proc=1.18.5
  - r-processx=3.8.4
  - r-prodlim=2024.06.25
  - r-progress=1.2.2
  - r-progressr=0.13.0
  - r-promises=1.3.0
  - r-proxy=0.4_27
  - r-pryr=0.1.6
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-quantmod=0.4.22
  - r-r6=2.5.1
  - r-ragg=1.2.5
  - r-randomforest=4.7_1.1
  - r-rappdirs=0.3.3
  - r-rbokeh=0.5.2
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-recipes=1.0.6
  - r-recommended=4.1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-repr=1.1.6
  - r-reprex=2.0.2
  - r-reshape2=1.4.4
  - r-rlang=1.1.4
  - r-rmarkdown=2.22
  - r-rpart=4.1.23
  - r-rstudioapi=0.14
  - r-rvest=1.0.3
  - r-sass=0.4.9
  - r-scales=1.2.1
  - r-selectr=0.4_2
  - r-shape=1.4.6
  - r-shiny=1.7.4
  - r-sourcetools=0.1.7_1
  - r-spatial=7.3_17
  - r-squarem=2021.1
  - r-stringi=1.8.4
  - r-stringr=1.5.0
  - r-survival=3.7_0
  - r-sys=3.4.2
  - r-systemfonts=1.1.0
  - r-textshaping=0.3.6
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4022.108
  - r-tinytex=0.45
  - r-triebeard=0.4.1
  - r-ttr=0.24.4
  - r-tzdb=0.4.0
  - r-urltools=1.7.3
  - r-utf8=1.2.4
  - r-uuid=1.2_0
  - r-vctrs=0.6.5
  - r-viridislite=0.4.1
  - r-vroom=1.6.5
  - r-withr=2.5.0
  - r-xfun=0.45
  - r-xml2=1.3.3
  - r-xtable=1.8_4
  - r-xts=0.14.0
  - r-yaml=2.3.8
  - r-zoo=1.8_12
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - seaborn=0.13.2
  - selenium=4.24.0
  - send2trash=1.8.3
  - setuptools=75.8.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trio=0.26.2
  - trio-websocket=0.11.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - vc=14.42
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wsproto=1.2.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6

